In [1]:
pip install sklearn

In [2]:
pip install seaborn

In [3]:
pip install pandas

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv("t1.csv")

In [8]:
df

Date/Time  LV ActivePower (kW)  Wind Speed (m/s)  \
0      01 01 2018 00:00           380.047791          5.311336   
1      01 01 2018 00:10           453.769196          5.672167   
2      01 01 2018 00:20           306.376587          5.216037   
3      01 01 2018 00:30           419.645905          5.659674   
4      01 01 2018 00:40           380.650696          5.577941   
...                 ...                  ...               ...   
50525  31 12 2018 23:10          2963.980957         11.404030   
50526  31 12 2018 23:20          1684.353027          7.332648   
50527  31 12 2018 23:30          2201.106934          8.435358   
50528  31 12 2018 23:40          2515.694092          9.421366   
50529  31 12 2018 23:50          2820.466064          9.979332   

       Theoretical_Power_Curve (KWh)  Wind Direction (°)  
0                         416.328908          259.994904  
1                         519.917511          268.641113  
2                         390.900016          272.564789  
3                         516.127569          271.258087  
4                         491.702972          265.674286  
...                              ...                 ...  
50525                    3397.190793           80.502724  
50526                    1173.055771           84.062599  
50527                    1788.284755           84.742500  
50528                    2418.382503           84.297913  
50529                    2779.184096           82.274620  

[50530 rows x 5 columns]

In [9]:
df = df.rename(columns={"LV ActivePower (kW)":"ap","Wind Speed (m/s)":"velo","Theoretical_Power_Curve (KWh)":"tpc"})

In [10]:
df['date'] = [d[:d.rfind(' ')] for d in df['Date/Time']]
df['time'] = [d[d.rfind(' '):] for d in df['Date/Time']]
df["vcube"] = df["velo"]**3
np.seterr(all='warn')


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [11]:
data = df[::]
data

Date/Time           ap       velo          tpc  \
0      01 01 2018 00:00   380.047791   5.311336   416.328908   
1      01 01 2018 00:10   453.769196   5.672167   519.917511   
2      01 01 2018 00:20   306.376587   5.216037   390.900016   
3      01 01 2018 00:30   419.645905   5.659674   516.127569   
4      01 01 2018 00:40   380.650696   5.577941   491.702972   
...                 ...          ...        ...          ...   
50525  31 12 2018 23:10  2963.980957  11.404030  3397.190793   
50526  31 12 2018 23:20  1684.353027   7.332648  1173.055771   
50527  31 12 2018 23:30  2201.106934   8.435358  1788.284755   
50528  31 12 2018 23:40  2515.694092   9.421366  2418.382503   
50529  31 12 2018 23:50  2820.466064   9.979332  2779.184096   

       Wind Direction (°)        date    time        vcube  
0              259.994904  01 01 2018   00:00   149.834333  
1              268.641113  01 01 2018   00:10   182.493326  
2              272.564789  01 01 2018   00:20   141.912921  
3              271.258087  01 01 2018   00:30   181.290183  
4              265.674286  01 01 2018   00:40   173.548848  
...                   ...         ...     ...          ...  
50525           80.502724  31 12 2018   23:10  1483.115712  
50526           84.062599  31 12 2018   23:20   394.259781  
50527           84.742500  31 12 2018   23:30   600.220141  
50528           84.297913  31 12 2018   23:40   836.260513  
50529           82.274620  31 12 2018   23:50   993.812397  

[50530 rows x 8 columns]

In [19]:
def cost_function(X, y, theta):
    m = len(y)
    y_pred = X.dot(theta)
    error = (y_pred - y) ** 2
    return 1 / (2 * m) * np.sum(error)

In [20]:
def gradient_descent(x, y, theta, alpha, iterations): 
    m = len(y)
    costs = []
    for i in range(iterations):
        y_pred = x.dot(theta)
        error = np.dot(x.transpose(), (y_pred - y))
        theta -= alpha * 1/m * error
        costs.append(cost_function(x, y, theta))
        
    return theta, costs

In [21]:
wd = df.iloc[:,-4].values
wd

array([259.99490356, 268.64111328, 272.56478882, ...,  84.74250031,
        84.2979126 ,  82.27462006])

In [22]:
m=data.vcube.values.size
x = np.append(np.ones((m, 1)), data.vcube.values.reshape(m,1), axis=1)
y = data["ap"].values.reshape(m,1)
theta = np.zeros((2,1))
costs=[]
cost_function(x, y, theta)

1716276.7422258097

In [23]:
x.shape

(50530, 2)

In [24]:
theta,costs

(array([[0.],
        [0.]]),
 [])

In [25]:
theta, costs = gradient_descent(x, y, theta, alpha=0.01, iterations=32)

In [26]:
theta,costs

(array([[-2.49175889e+138],
        [-7.67725881e+141]]),
 [862800746263075.0,
  6.395300167717111e+23,
  4.740360325186529e+32,
  3.513676516081922e+41,
  2.604427050422543e+50,
  1.9304680524593038e+59,
  1.430912377047155e+68,
  1.060628912339845e+77,
  7.861653220252577e+85,
  5.827258774151179e+94,
  4.319313491651433e+103,
  3.2015858162879786e+112,
  2.3730974282992765e+121,
  1.7590006101195404e+130,
  1.3038163159691037e+139,
  9.664220558011726e+147,
  7.163367864780584e+156,
  5.309671779337787e+165,
  3.935664751060461e+174,
  2.917215541084093e+183,
  2.1623148950503212e+192,
  1.6027631964482578e+201,
  1.1880091423174747e+210,
  8.805828118324085e+218,
  6.527105397371199e+227,
  4.838057738117688e+236,
  3.5860923414516304e+245,
  2.6581035154039743e+254,
  1.9702544234382115e+263,
  1.4604030545017638e+272,
  1.0824881579893909e+281,
  8.023679549116198e+289])

In [27]:
x = data[["vcube","Wind Direction (°)"]]
y = data["ap"]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,y_train,x_test,y_test = train_test_split(x,y,test_size=0.4)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
model = LinearRegression()

In [32]:
model.fit(x,y)

LinearRegression()

In [33]:
model.intercept_

873.2259192944637

In [34]:
model.coef_

array([ 0.70797852, -1.54552334])

In [35]:
model.predict([[149.834333,259.994904]])

array([577.47721555])

In [36]:
pip install watson_machine_learning_client

In [41]:
pip install sklearn

In [42]:
import sklearn.external.joblib as extjoblib
import joblib

ModuleNotFoundError: No module named 'sklearn.external'

In [38]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

ImportError: cannot import name 'joblib' from 'sklearn.externals' (c:\users\ragav\appdata\local\programs\python\python38\lib\site-packages\sklearn\externals\__init__.py)